/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 back.gltf 
Author: stylized skybox (https://sketchfab.com/skybox_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-stylized-skybox-cityskyline-001-e7f1513513c54f65b1614e838f941a90
Title: FREE Stylized Skybox CitySkyLine 001
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/back/back.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/back/back.gltf')
